### PR TITLE
Unicode support

### LINKED ISSUE #5: Can't encode unicode characters
Example minimum working dataframe:

`df = pd.DataFrame(["абв"])`
`dfi.export(df, df.png', max_rows = 1)`

---------------------------------------------------------------------------------------------------------------
```
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-79-48c9f88e0332> in <module>
----> 1 dfi.export(df, 'smirnov_sent_df.png', max_rows = 1)

~\Anaconda3\lib\site-packages\dataframe_image\_pandas_accessor.py in export(obj, filename, fontsize, max_rows, max_cols, table_conversion, chrome_path)
     22 def export(obj, filename, fontsize=14, max_rows=None, max_cols=None, 
     23                table_conversion='chrome', chrome_path=None):
---> 24         return _export(obj, filename, fontsize, max_rows, max_cols, table_conversion, chrome_path)
     25 
     26 

~\Anaconda3\lib\site-packages\dataframe_image\_pandas_accessor.py in _export(obj, filename, fontsize, max_rows, max_cols, table_conversion, chrome_path)
     71         html = obj.to_html(max_rows=max_rows, max_cols=max_cols, notebook=True)
     72 
---> 73     img_str = converter(html)
     74 
     75     if isinstance(filename, str):

~\Anaconda3\lib\site-packages\dataframe_image\_screenshot.py in run(self, html)
    165     def run(self, html):
    166         self.html = self.css + html
--> 167         img = self.take_screenshot()
    168         img_str = self.finalize_image(img)
    169         return img_str

~\Anaconda3\lib\site-packages\dataframe_image\_screenshot.py in take_screenshot(self)
     93         temp_img = Path(temp_dir.name) / "temp.png"
     94         with open(temp_html, "w") as f:
---> 95             f.write(self.html)
     96 
     97         with open(temp_img, "wb") as f:

~\Anaconda3\lib\encodings\cp1252.py in encode(self, input, final)
     17 class IncrementalEncoder(codecs.IncrementalEncoder):
     18     def encode(self, input, final=False):
---> 19         return codecs.charmap_encode(input,self.errors,encoding_table)[0]
     20 
     21 class IncrementalDecoder(codecs.IncrementalDecoder):

UnicodeEncodeError: 'charmap' codec can't encode characters in position 1296-1298: character maps to <undefined>
```

### PR DESCRIPTION
**Pull request by moshemoshe137**
Add Unicode support. Resolves #5.

### CODE REVIEW

**Comment by rdmolony** [comment]
It might be better to add encoding as a parameter to the `export` function for cases other than `utf-8`

**Comment by PaleNeutron** [comment]
@tdpetrou Maybe I can, I will use this lib quite frequently for about 1 year and the up-to-date support is vital. I can maintain this project until you are free.

**Comment by tdpetrou** [comment]
Hey @PaleNeutron, that would be great! Why don't we start a discussion here on what you can do to help out.

**Comment by PaleNeutron** [comment]
@tdpetrou , Maybe the most emergency things are merge these pr into this repo and publish a new release😋.

In fact, I have merged them into my fork and they works well.

**Comment by tdpetrou** [comment]
@PaleNeutron Excellent. Can I add you as an a collaborator so you can incorporate these changes?

**Comment by PaleNeutron** [comment]
@tdpetrou Sure, let's make this project better together!

**Comment by tdpetrou** [comment]
Great! Just added you as a maintainer. Feel free to take on as many issues as you'd like and merge pull requests. I haven't looked at this project in a long time. I really appreciate the help!

**Pull request merged**
